add re-exports of modemmanager-sys types
omnect/modemmanager pull request #4
Opened 2024-02-26 07:53 UTC by empwilli

2024-02-26 08:25 UTC, JanZachmann requested changes

2024-02-26 08:25 UTC, JanZachmann commented on src/types.rs
> +
rm empty line

2024-02-26 08:25 UTC, JanZachmann commented on src/types.rs
> +pub use modemmanager_sys::MMBearerType as BearerType;
not sure, but I guess you could write:
```
#[cfg(feature = "ModemManager-1_22")]
pub use modemmanager_sys::{
    MMBearerAccessTypePreference as BearerAccessTypePreference,
    MMBearerProfileSource as BearerProfileSource,
    MMBearerRoamingAllowance as BearerRoamingAllowance
}
pub use modemmanager_sys::{
    MMBearerAllowedAuth as BearerAllowedAuth,
    ....
}
```

2024-02-26 12:17 UTC, mlilien approved these changes

2024-03-04 08:44 UTC, JanZachmann approved these changes

2024-03-18 09:39 UTC, merged